# Vue + Nginx 프론트를 Kubernetes에서 실행
apiVersion: apps/v1
kind: Deployment

metadata:
  name: beatbuddy-frontend

spec:
  replicas: 1

  selector:
    matchLabels:
      app: frontend

  template:
    metadata:
      labels:
        app: frontend

    spec:
      imagePullSecrets:
        - name: dockerhub-secret

      containers:
        - name: frontend
          image: whiteyan/beatbuddy-frontend:dev
          imagePullPolicy: Always

          ports:
            - containerPort: 80